Импортируйте библиотеку NumPy

In [ ]:
import numpy as np


Создайте массив из 10 нулей

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать массив из 10 единиц

In [ ]:
b = np.ones(10)
print (b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать массив из 10 пятерок

In [ ]:
C = [5]*10
print (C)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


Создать массив из целых чисел от 10 до 50

In [ ]:
D = list(range(10,51))
print (D)

Создать массив из четных чисел от 10 до 50

In [ ]:
i = 10
while i <= 50:
    if i % 2 == 0:
        print(i)
    i += 1


Создать матрицу 3х3 с числами от 0 до 8

In [ ]:
F = np.arange(9).reshape(3,3) 
print(F)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Создать единичную матрицу 3x3

In [ ]:
A_eye = np.eye(3)
print(A_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Используйте NumPy для генерации случайного числа от 0 до 1

In [ ]:
import random
G = random.random()
print (G)

0.4051045464781057


Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

In [ ]:
H = np.random.randn(1, 25)
print (H)

[[ 0.94356481 -0.14554843  0.15397905  1.01522538 -0.19591122 -0.25868087
   0.0291124  -0.34592353 -2.33532485 -0.12585623  0.59813456  0.04738546
  -0.53535744  1.11165985 -0.5274294  -0.17042575  0.15982453  0.86902084
   0.32966514 -0.3974178   0.28028541  1.03873721 -0.29459021 -0.84521915
   1.33171268]]


Создайте следующую матрицу используя функции библиотеки NumPy


In [ ]:
np.linspace(0.01, 1.0, 100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). Эта матрица будет использоваться в последующих задачах

In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Необходимо написать код который вернет следующую матрицу из стартовой

In [ ]:
print(mat[2:5, 1:5]) 

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи

In [ ]:
print(mat[3][4])

20


Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [ ]:
print(mat[0][1])  
print( mat[1][1])
print(mat[2][1])

2
7
12


In [ ]:
print(np.array([mat[0, 1], mat[1, 1], mat[2, 1]]))

[ 2  7 12]


Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [ ]:
print(mat[-1])

[21 22 23 24 25]


Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [ ]:
print(mat[3])
print(mat[-1])

[16 17 18 19 20]
[21 22 23 24 25]


Получить сумму всех значений в стартовой матрице mat

In [ ]:
np.sum(mat)

325

Получить стандартное отклонение в стартовой матрице mat

In [ ]:
arr = np.array(mat)
dev = np.std(arr)
print(dev)

7.211102550927978


Получить сумму значений в колонках в стартовой матрице mat

In [ ]:
np.sum(mat, axis = 0) 

array([55, 60, 65, 70, 75])